import React, { useState, useEffect } from 'react';
import { FileSystemItem } from '@/lib/data';
import { Github, Star, GitFork, ExternalLink, Globe, Edit, Save, X, ShieldCheck, Download, CheckCircle, Loader2, PieChart, Activity, Database, Code } from 'lucide-react';
import ScrambleText from './ScrambleText';

interface DataViewerProps {
  item: FileSystemItem | null;
  isAdmin?: boolean;
  onUpdate?: () => void;
  dashboardStats?: {
    totalRepos: number;
    totalStars: number;
    languages: Record<string, number>;
    recentUpdate: string;
  };
  specialMode?: 'timeline' | 'search' | null;
  specialData?: any;
  isBookmarked?: boolean;
  onToggleBookmark?: () => void;
}

const DataViewer = ({ item, isAdmin, onUpdate, dashboardStats, specialMode, specialData, isBookmarked, onToggleBookmark }: DataViewerProps) => {
  const [viewMode, setViewMode] = useState<'text' | 'hex' | 'preview'>('text');
  const [isEditing, setIsEditing] = useState(false);
  const [verificationState, setVerificationState] = useState<'idle' | 'verifying' | 'verified'>('idle');
  const [editForm, setEditForm] = useState({
    longDescription: '',
    features: '',
    teamInfo: ''
  });

  useEffect(() => {
    if (item?.type === 'repo') {
      setViewMode('preview');
    } else {
      setViewMode('text');
    }

    if (item?.repoInfo) {
      setEditForm({
        longDescription: item.repoInfo.longDescription || '',
        features: item.repoInfo.features ? item.repoInfo.features.join('\n') : '',
        teamInfo: item.repoInfo.teamInfo || ''
      });
    }
    setIsEditing(false);
    setVerificationState('idle');
  }, [item]);

  const handleVerify = () => {
    setVerificationState('verifying');
    setTimeout(() => {
      setVerificationState('verified');
    }, 1500);
  };

  const handleDownloadReport = () => {
    if (!item) return;
    const content = `PROJECT REPORT: ${item.name}
Last Updated: ${item.dateModified}
Language: ${item.repoInfo?.language}
URL: ${item.repoInfo?.url}

[1] OVERVIEW
${item.repoInfo?.longDescription || item.repoInfo?.description || "No description available."}

[2] KEY FEATURES
${item.repoInfo?.features ? item.repoInfo.features.map(f => `- ${f}`).join('\n') : "No features listed."}

[3] TEAM INFORMATION
${item.repoInfo?.teamInfo || "No team information provided."}

Generated by FTK Portfolio System`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${item.name}_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    if (!item) return;
    try {
      const res = await fetch(`/api/repos/${item.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          longDescription: editForm.longDescription,
          features: editForm.features.split('\n').filter(f => f.trim() !== ''),
          teamInfo: editForm.teamInfo
        })
      });
      if (res.ok) {
        setIsEditing(false);
        if (onUpdate) onUpdate();
      } else {
        alert('Failed to save changes');
      }
    } catch (error) {
      console.error(error);
      alert('Error saving changes');
    }
  };

  if (specialMode === 'timeline' && specialData) {
    return (
      <div className="h-full bg-gray-100 p-6 overflow-auto">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
            <Activity className="mr-2 text-blue-600" />
            <ScrambleText text="TIMELINE RECONSTRUCTION" speed={40} />
          </h1>
          <div className="relative border-l-2 border-blue-300 ml-3 space-y-8 pb-8">
            {specialData.map((event: any, idx: number) => (
              <div key={event.id || idx} className="relative pl-8">
                <div className={`absolute -left-[9px] top-0 w-4 h-4 rounded-full border-2 ${event.type === 'REPO_MODIFIED' ? 'bg-blue-500 border-blue-200' : 'bg-green-500 border-green-200'}`}></div>
                <div className="text-xs text-gray-500 mb-1 font-mono">{new Date(event.timestamp).toLocaleString()}</div>
                <div className="bg-white p-3 rounded shadow-sm border border-gray-200">
                  <div className="font-bold text-sm text-gray-800 mb-1">{event.type}</div>
                  <div className="text-xs text-gray-600">{event.details}</div>
                  <div className="text-[10px] text-gray-400 mt-2 font-mono">Source: {event.source}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (specialMode === 'search' && specialData) {
    return (
      <div className="h-full bg-gray-100 p-6 overflow-auto">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
            <ShieldCheck className="mr-2 text-purple-600" />
            <ScrambleText text={`SEARCH RESULTS: ${specialData.query || ''}`} speed={40} />
          </h1>
          
          <div className="mb-8">
            <h2 className="text-lg font-bold text-gray-700 mb-4 border-b border-gray-300 pb-2">Repositories Found ({specialData.repos?.length || 0})</h2>
            {specialData.repos?.length > 0 ? (
              <div className="grid grid-cols-1 gap-4">
                {specialData.repos.map((repo: any) => (
                  <div key={repo._id} className="bg-white p-4 rounded shadow-sm border border-gray-200 hover:border-blue-400 transition-colors cursor-pointer">
                    <div className="flex justify-between items-start">
                      <h3 className="font-bold text-blue-700">{repo.name}</h3>
                      <span className="text-xs bg-gray-100 px-2 py-1 rounded">{repo.language}</span>
                    </div>
                    <p className="text-xs text-gray-600 mt-2 line-clamp-2">{repo.description}</p>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-500 italic text-sm">No repositories found matching criteria.</p>
            )}
          </div>

          <div>
            <h2 className="text-lg font-bold text-gray-700 mb-4 border-b border-gray-300 pb-2">Log Entries Found ({specialData.logs?.length || 0})</h2>
            {specialData.logs?.length > 0 ? (
              <div className="space-y-2">
                {specialData.logs.map((log: any) => (
                  <div key={log._id} className="bg-white p-3 rounded shadow-sm border border-gray-200 font-mono text-xs">
                    <div className="flex justify-between text-gray-500 mb-1">
                      <span>{new Date(log.timestamp).toLocaleString()}</span>
                      <span>{log.userId}</span>
                    </div>
                    <div className="text-gray-800">
                      <span className="font-bold text-blue-600">{log.action}:</span> {log.details}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-500 italic text-sm">No log entries found matching criteria.</p>
            )}
          </div>
        </div>
      </div>
    );
  }

  if (!item) {
    if (dashboardStats) {
      return (
        <div className="h-full bg-gray-100 p-6 overflow-auto">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
              <Activity className="mr-2 text-blue-600" />
              <ScrambleText text="CASE DASHBOARD: SUMMARY" speed={40} />
            </h1>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
              <div className="bg-white p-4 rounded shadow-sm border border-gray-200">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xs font-bold text-gray-500 uppercase">Total Evidence Items</h3>
                  <Database size={16} className="text-blue-500" />
                </div>
                <p className="text-2xl font-bold text-gray-800">{dashboardStats.totalRepos}</p>
                <p className="text-xs text-gray-400 mt-1">Repositories Indexed</p>
              </div>
              
              <div className="bg-white p-4 rounded shadow-sm border border-gray-200">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xs font-bold text-gray-500 uppercase">Total Impact Score</h3>
                  <Star size={16} className="text-yellow-500" />
                </div>
                <p className="text-2xl font-bold text-gray-800">{dashboardStats.totalStars}</p>
                <p className="text-xs text-gray-400 mt-1">Total Stars Acquired</p>
              </div>

              <div className="bg-white p-4 rounded shadow-sm border border-gray-200">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xs font-bold text-gray-500 uppercase">Last Activity</h3>
                  <Activity size={16} className="text-green-500" />
                </div>
                <p className="text-sm font-bold text-gray-800 mt-1">{dashboardStats.recentUpdate}</p>
                <p className="text-xs text-gray-400 mt-1">Most Recent Commit</p>
              </div>
            </div>

            <div className="bg-white p-6 rounded shadow-sm border border-gray-200 mb-8">
              <h3 className="text-sm font-bold text-gray-700 mb-4 flex items-center">
                <Code size={16} className="mr-2 text-purple-500" />
                <ScrambleText text="LANGUAGE DISTRIBUTION" delay={500} />
              </h3>
              <div className="space-y-3">
                {Object.entries(dashboardStats.languages).sort(([,a], [,b]) => b - a).map(([lang, count]) => (
                  <div key={lang}>
                    <div className="flex justify-between text-xs mb-1">
                      <span className="font-medium text-gray-700">{lang}</span>
                      <span className="text-gray-500">{count} repos ({Math.round((count / dashboardStats.totalRepos) * 100)}%)</span>
                    </div>
                    <div className="w-full bg-gray-100 rounded-full h-2">
                      <div 
                        className="bg-blue-600 h-2 rounded-full" 
                        style={{ width: `${(count / dashboardStats.totalRepos) * 100}%` }}
                      ></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="text-center text-xs text-gray-400 mt-8">
              FTK Portfolio System v1.0.0 | Authorized Access Only
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="h-full bg-white border border-gray-400 flex items-center justify-center text-gray-400 text-xs">
        No item selected
      </div>
    );
  }

  // Simple hex view simulation
  const renderHex = (content: string) => {
    const text = content.replace(/<[^>]*>/g, ''); // Strip HTML for hex view
    const encoder = new TextEncoder();
    const data = encoder.encode(text);
    
    const hexLines = [];
    for (let i = 0; i < data.length; i += 16) {
      const chunk = data.slice(i, i + 16);
      const hex = Array.from(chunk).map(b => b.toString(16).padStart(2, '0')).join(' ');
      const ascii = Array.from(chunk).map(b => (b >= 32 && b <= 126) ? String.fromCharCode(b) : '.').join('');
      
      hexLines.push(
        <div key={i} className="flex">
          <span className="w-16 text-blue-800 select-none">{i.toString(16).padStart(8, '0')}</span>
          <span className="w-96 text-gray-800 mx-4">{hex.padEnd(47, ' ')}</span>
          <span className="text-gray-600">{ascii}</span>
        </div>
      );
    }
    return hexLines;
  };

  const renderRepoCard = () => {
    if (!item.repoInfo) return null;
    
    return (
      <div className="p-4 max-w-2xl mx-auto mt-4">
        <div className="border border-gray-300 rounded-lg shadow-sm bg-white overflow-hidden relative">
          {isAdmin && (
            <div className="absolute top-2 right-2 z-10">
              {isEditing ? (
                <div className="flex space-x-1">
                  <button onClick={handleSave} className="p-1 bg-green-100 text-green-600 rounded hover:bg-green-200" title="Save">
                    <Save size={16} />
                  </button>
                  <button onClick={() => setIsEditing(false)} className="p-1 bg-red-100 text-red-600 rounded hover:bg-red-200" title="Cancel">
                    <X size={16} />
                  </button>
                </div>
              ) : (
                <button onClick={() => setIsEditing(true)} className="p-1 bg-gray-100 text-gray-600 rounded hover:bg-gray-200" title="Edit Details">
                  <Edit size={16} />
                </button>
              )}
            </div>
          )}

          <div className="bg-gray-50 px-4 py-3 border-b border-gray-200 flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <Github size={20} className="text-gray-700" />
              <span className="font-bold text-blue-600 text-sm">{item.name}</span>
              <span className="text-xs border border-gray-300 rounded-full px-2 py-0.5 text-gray-500">Public</span>
            </div>
            <div className="flex items-center space-x-3 mr-8">
              {item.repoInfo.homepage && (
                <a 
                  href={item.repoInfo.homepage} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-xs flex items-center text-green-600 hover:text-green-800 font-medium bg-green-50 px-2 py-1 rounded border border-green-200"
                >
                  <Globe size={14} className="mr-1" />
                  Live Demo
                </a>
              )}
              <a 
                href={item.repoInfo.url} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-xs flex items-center text-gray-600 hover:text-blue-600"
              >
                <ExternalLink size={14} className="mr-1" />
                View on GitHub
              </a>
            </div>
          </div>
          <div className="p-4">
            <p className="text-sm text-gray-700 mb-4">{item.repoInfo.description}</p>
            
            {/* Extended Info Section */}
            {isEditing ? (
              <div className="space-y-4 mb-4 border-t pt-4">
                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Detailed Description</label>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-2 text-xs" 
                    rows={3}
                    value={editForm.longDescription}
                    onChange={e => setEditForm({...editForm, longDescription: e.target.value})}
                    placeholder="Enter detailed project description..."
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Key Features (One per line)</label>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-2 text-xs" 
                    rows={3}
                    value={editForm.features}
                    onChange={e => setEditForm({...editForm, features: e.target.value})}
                    placeholder="- User Authentication&#10;- CRUD Operations&#10;- Real-time updates"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Team Information</label>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-2 text-xs" 
                    rows={2}
                    value={editForm.teamInfo}
                    onChange={e => setEditForm({...editForm, teamInfo: e.target.value})}
                    placeholder="Team Lead: Alice, Backend: Bob..."
                  />
                </div>
              </div>
            ) : (
              (item.repoInfo.longDescription || (item.repoInfo.features && item.repoInfo.features.length > 0) || item.repoInfo.teamInfo) && (
                <div className="space-y-4 mb-4 border-t pt-4">
                  {item.repoInfo.longDescription && (
                    <div>
                      <h4 className="font-bold text-xs text-gray-800 mb-1">Project Overview</h4>
                      <p className="text-xs text-gray-600 whitespace-pre-wrap">{item.repoInfo.longDescription}</p>
                    </div>
                  )}
                  {item.repoInfo.features && item.repoInfo.features.length > 0 && (
                    <div>
                      <h4 className="font-bold text-xs text-gray-800 mb-1">Key Features</h4>
                      <ul className="list-disc list-inside text-xs text-gray-600">
                        {item.repoInfo.features.map((feature, idx) => (
                          <li key={idx}>{feature}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {item.repoInfo.teamInfo && (
                    <div>
                      <h4 className="font-bold text-xs text-gray-800 mb-1">Team</h4>
                      <p className="text-xs text-gray-600 whitespace-pre-wrap">{item.repoInfo.teamInfo}</p>
                    </div>
                  )}
                </div>
              )
            )}

            <div className="flex items-center space-x-4 text-xs text-gray-600">
              <div className="flex items-center">
                <span className="w-3 h-3 rounded-full bg-yellow-400 mr-1"></span>
                {item.repoInfo.language}
              </div>
              <div className="flex items-center hover:text-blue-600 cursor-pointer">
                <Star size={14} className="mr-1" />
                {item.repoInfo.stars}
              </div>
              <div className="flex items-center hover:text-blue-600 cursor-pointer">
                <GitFork size={14} className="mr-1" />
                {Math.floor(item.repoInfo.stars * 0.2)}
              </div>
            </div>
          </div>
          <div className="bg-gray-50 px-4 py-2 border-t border-gray-200 text-xs text-gray-500">
            Last updated on {item.dateModified}
          </div>
        </div>
        
        <div className="mt-6 border-t border-gray-200 pt-4">
          <h3 className="font-bold text-sm mb-2 flex items-center">
            <span className="mr-2">README.md</span>
          </h3>
          <div className="bg-white border border-gray-200 rounded overflow-hidden p-4">
            {item.repoInfo.homepage && (
               <div className="mb-4 pb-3 border-b border-gray-100 flex items-center">
                 <span className="text-xs text-gray-500 mr-2 font-semibold">Deployment URL:</span>
                 <a href={item.repoInfo.homepage} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-xs flex items-center">
                   <Globe size={12} className="mr-1" />
                   {item.repoInfo.homepage}
                 </a>
               </div>
            )}
            <div 
              className="prose prose-sm max-w-none"
              dangerouslySetInnerHTML={{ __html: item.content || '' }} 
            />
          </div>
        </div>
      </div>
    );
  };

  const renderRepoTextReport = () => {
    if (!item?.repoInfo) return null;
    
    return (
      <div className="p-6 font-mono text-sm bg-white h-full overflow-auto relative">
          {isAdmin && (
            <div className="absolute top-4 right-4 z-10">
              {isEditing ? (
                <div className="flex space-x-2">
                  <button onClick={handleSave} className="flex items-center px-2 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200 border border-green-300" title="Save">
                    <Save size={14} className="mr-1" /> Save
                  </button>
                  <button onClick={() => setIsEditing(false)} className="flex items-center px-2 py-1 bg-red-100 text-red-700 rounded hover:bg-red-200 border border-red-300" title="Cancel">
                    <X size={14} className="mr-1" /> Cancel
                  </button>
                </div>
              ) : (
                <button onClick={() => setIsEditing(true)} className="flex items-center px-2 py-1 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 border border-gray-300" title="Edit Report">
                  <Edit size={14} className="mr-1" /> Edit Report
                </button>
              )}
            </div>
          )}

          {isEditing ? (
              <div className="space-y-6 max-w-3xl mt-8">
                <div>
                  <label className="block font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">PROJECT DESCRIPTION</label>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-3 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none" 
                    rows={6}
                    value={editForm.longDescription}
                    onChange={e => setEditForm({...editForm, longDescription: e.target.value})}
                    placeholder="Enter detailed project description..."
                  />
                </div>
                <div>
                  <label className="block font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">KEY FEATURES</label>
                  <p className="text-xs text-gray-500 mb-2">Enter one feature per line</p>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-3 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none" 
                    rows={6}
                    value={editForm.features}
                    onChange={e => setEditForm({...editForm, features: e.target.value})}
                    placeholder="- User Authentication&#10;- CRUD Operations&#10;- Real-time updates"
                  />
                </div>
                <div>
                  <label className="block font-bold text-gray-800 mb-2 border-b border-gray-300 pb-1">TEAM INFORMATION</label>
                  <textarea 
                    className="w-full border border-gray-300 rounded p-3 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none" 
                    rows={3}
                    value={editForm.teamInfo}
                    onChange={e => setEditForm({...editForm, teamInfo: e.target.value})}
                    placeholder="Team Lead: Alice, Backend: Bob..."
                  />
                </div>
              </div>
          ) : (
              <div className="max-w-4xl">
                  <div className="mb-8 border-b-2 border-gray-800 pb-4 flex justify-between items-end">
                      <div>
                          <h1 className="text-2xl font-bold text-gray-900 mb-2">
                            <ScrambleText text={`PROJECT REPORT: ${item.name}`} speed={30} />
                          </h1>
                          <div className="text-gray-600 flex space-x-4 text-xs">
                              <span>Last Updated: {item.dateModified}</span>
                              <span>|</span>
                              <span>Language: {item.repoInfo.language}</span>
                              <span>|</span>
                              <span>Size: {item.size}</span>
                          </div>
                      </div>
                      <button 
                        onClick={handleDownloadReport}
                        className="flex items-center px-3 py-1.5 bg-blue-50 text-blue-700 rounded hover:bg-blue-100 border border-blue-200 text-xs font-bold transition-colors mr-2"
                      >
                        <Download size={14} className="mr-1.5" /> Export Report
                      </button>
                      {onToggleBookmark && (
                        <button 
                          onClick={onToggleBookmark}
                          className={`flex items-center px-3 py-1.5 rounded border text-xs font-bold transition-colors ${isBookmarked ? 'bg-yellow-100 text-yellow-700 border-yellow-300' : 'bg-gray-50 text-gray-600 border-gray-300 hover:bg-gray-100'}`}
                        >
                          <Star size={14} className={`mr-1.5 ${isBookmarked ? 'fill-yellow-500 text-yellow-500' : ''}`} /> 
                          {isBookmarked ? 'Bookmarked' : 'Bookmark'}
                        </button>
                      )}
                  </div>

                  {/* Integrity Section */}
                  <div className="mb-8 bg-gray-50 p-4 rounded border border-gray-200">
                      <h2 className="text-sm font-bold text-gray-700 mb-2 flex items-center">
                        <ShieldCheck size={16} className="mr-2 text-gray-500" />
                        EVIDENCE INTEGRITY CHECK
                      </h2>
                      <div className="flex items-center justify-between">
                        <div className="font-mono text-xs text-gray-600">
                          <span className="font-bold mr-2">MD5 HASH:</span>
                          {/* Fake hash based on name/id to look consistent */}
                          {item.id.substring(0, 8).toUpperCase()}-{item.name.length}F-88A2-91B0-{item.repoInfo.stars}C
                        </div>
                        <div>
                          {verificationState === 'idle' && (
                            <button 
                              onClick={handleVerify}
                              className="px-3 py-1 bg-white border border-gray-300 rounded text-xs hover:bg-gray-100 shadow-sm transition-all"
                            >
                              Verify Hash
                            </button>
                          )}
                          {verificationState === 'verifying' && (
                            <div className="flex items-center text-blue-600 text-xs">
                              <Loader2 size={14} className="animate-spin mr-2" /> Verifying...
                            </div>
                          )}
                          {verificationState === 'verified' && (
                            <div className="flex items-center text-green-600 text-xs font-bold">
                              <CheckCircle size={14} className="mr-2" /> Verified Match
                            </div>
                          )}
                        </div>
                      </div>
                  </div>
                  
                  <div className="mb-8">
                      <h2 className="text-lg font-bold text-gray-800 mb-3 border-b border-gray-200 pb-1">
                        <ScrambleText text="[1] OVERVIEW" delay={500} />
                      </h2>
                      <div className="pl-4 text-gray-700 leading-relaxed whitespace-pre-wrap">
                          {item.repoInfo.longDescription || item.repoInfo.description || "No description available."}
                      </div>
                  </div>

                  <div className="mb-8">
                      <h2 className="text-lg font-bold text-gray-800 mb-3 border-b border-gray-200 pb-1">
                        <ScrambleText text="[2] KEY FEATURES" delay={1000} />
                      </h2>
                      <div className="pl-4 text-gray-700">
                          {item.repoInfo.features && item.repoInfo.features.length > 0 ? (
                              <ul className="list-disc list-inside space-y-1">
                                  {item.repoInfo.features.map((f, i) => <li key={i}>{f}</li>)}
                              </ul>
                          ) : (
                              <p className="italic text-gray-500">No features listed.</p>
                          )}
                      </div>
                  </div>

                  <div className="mb-8">
                      <h2 className="text-lg font-bold text-gray-800 mb-3 border-b border-gray-200 pb-1">
                        <ScrambleText text="[3] TEAM INFORMATION" delay={1500} />
                      </h2>
                      <div className="pl-4 text-gray-700 whitespace-pre-wrap">
                          {item.repoInfo.teamInfo || "No team information provided."}
                      </div>
                  </div>
                  
                  <div className="mt-12 pt-4 border-t border-gray-300 text-xs text-gray-500 text-center">
                      Generated by FTK Portfolio System
                  </div>
              </div>
          )}
      </div>
    );
  };

  const renderContent = () => {
    if (viewMode === 'hex') {
      let contentToHex = item.content || '';
      
      // For repos, we want the HEX view to reflect the "Project Report" seen in the TEXT view
      if (item.type === 'repo') {
          contentToHex = `PROJECT REPORT: ${item.name}\n`;
          contentToHex += `Last Updated: ${item.dateModified} | Language: ${item.repoInfo?.language} | Size: ${item.size}\n\n`;
          
          contentToHex += `[1] OVERVIEW\n`;
          contentToHex += `${item.repoInfo?.longDescription || item.repoInfo?.description || "No description available."}\n\n`;
          
          contentToHex += `[2] KEY FEATURES\n`;
          if (item.repoInfo?.features && item.repoInfo.features.length > 0) {
              contentToHex += item.repoInfo.features.map(f => `- ${f}`).join('\n') + '\n\n';
          } else {
              contentToHex += `No features listed.\n\n`;
          }
          
          contentToHex += `[3] TEAM INFORMATION\n`;
          contentToHex += `${item.repoInfo?.teamInfo || "No team information provided."}\n\n`;
          
          contentToHex += `Generated by FTK Portfolio System`;
      }

      return (
        <div className="font-mono whitespace-pre">
          {contentToHex ? renderHex(contentToHex) : <span className="text-gray-400 italic">No data</span>}
        </div>
      );
    }

    if (item.type === 'repo') {
        if (viewMode === 'preview') return renderRepoCard();
        if (viewMode === 'text') return renderRepoTextReport();
    }

    if (item.contentType === 'code') {
      return (
        <pre className="font-mono text-sm bg-gray-50 p-2 border border-gray-200 overflow-auto">
          <code>{item.content}</code>
        </pre>
      );
    }

    return (
      <div 
        className="prose prose-sm max-w-none"
        dangerouslySetInnerHTML={{ __html: item.content || '<p class="text-gray-400 italic">No preview available</p>' }} 
      />
    );
  };

  return (
    <div className="h-full bg-white border border-gray-400 flex flex-col font-mono text-xs">
      <div className="bg-[#f0f0f0] px-2 py-1 border-b border-gray-300 flex justify-between items-center">
        <span className="font-bold">Data Viewer {item.name ? `- ${item.name}` : ''}</span>
        <div className="space-x-2">
          {item.type === 'repo' && (
            <button 
              className={`px-2 py-0.5 border ${viewMode === 'preview' ? 'bg-white border-gray-400 shadow-inner' : 'bg-gray-200 border-gray-300'}`}
              onClick={() => setViewMode('preview')}
            >
              Preview
            </button>
          )}
          <button 
            className={`px-2 py-0.5 border ${viewMode === 'text' ? 'bg-white border-gray-400 shadow-inner' : 'bg-gray-200 border-gray-300'}`}
            onClick={() => setViewMode('text')}
          >
            Text
          </button>
          <button 
            className={`px-2 py-0.5 border ${viewMode === 'hex' ? 'bg-white border-gray-400 shadow-inner' : 'bg-gray-200 border-gray-300'}`}
            onClick={() => setViewMode('hex')}
          >
            Hex
          </button>
        </div>
      </div>
      <div className="flex-1 overflow-auto p-2 bg-white">
        {renderContent()}
      </div>
    </div>
  );
};

export default DataViewer;
